### ISSUE TITLE
How delete folder in one command ?

### ISSUE THREAD

**Issue by kareemzok** [bilberrry/yii2-digitalocean-spaces#1]
How can we delete a folder in a single execution? 
I tried the following but it didn't work 

```
        $storage = Yii::$app->get('storage');
        $result = $storage->commands()->delete($folder_path)->execute();

```

Please advice

**Comment by alexmukho** [comment]
There's no such functionality at the moment. So the only way is to iterate over required objects and delete them one by one.

**Comment by kareemzok** [comment]
Thanks for your reply.
